name: Weekly Attendance Email

on:
  schedule:
    - cron: 0 19 * * 6   
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pymongo python-docx

      - name: Run email script
        run: python weekly_log.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
